### ISSUE TITLE
How to Run this project in my local visual code?

### ISSUE THREAD

**Issue by sirishkumarnampally** [techterbium/cowlogs#1]
Hello @techterbium ,

I have installed visual code and cloned this project. when i am trying to run npm isntall its failing as it does not contain package.json.

Could you please let us know the process how to run in my local.

Thanks,
Sirish.

**Comment by techterbium** [comment]
Hi @sirishkumarnampally , 

Recommended way to run this project is - you should install "Live Server" plugin in VSCode. Open index.html file, right click on the file (anywhere) and choose the option - "Open with Live Server"
